version: '3.8'
services:
  db:
    image: postgres:15-alpine
    container_name: voyis_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: voyis_data
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./images_storage:/usr/src/app/storage

volumes:
  pgdata: